# Pragmatism

The term *pragmatic* has come to mean in popular usage something similar to *practical*.  So to call a *theory* (i.e. a system of concepts) *pragmatic* is often taken to mean that the idea is close enough to the way things are so that they could be made actual, i.e. to be put into practice.  It is often used in contrast to *idealistic*, which is applied to a theory that cannot be put into practice.  Sometimes this judgement is rendered less harsh by bounding it in time, by stating that an *idealistic* theory may be preferred at some future date, but at the present time there is no path to the actual.  

Based on this common understanding of the meaning of the word *pragmatic*, you may have come to this text with the belief that *pragmatic ecosocialism* will primarily be concerned with the practical implementation of the theory of ecosocialism.  Please be assured that is absolutely the intent of this text.  But it is my belief that in order to accomplish this goal, it is very important to clarify the relationship between *theory* and *practice*.  In order to do this, this text must first develop the theory of *pragmaticism*, as first proposed by Charles Sanders Peirce, understood as a general method to understand the relationship between theory and practice.  Then, *pragmaticism* will be used to better understand the relationship between the *theory* and *practice* of *ecosocialism*.

One way to think of this process is to borrow the notion of *operator* from mathematics and consider *pragmatic* as an operator on a theory, considered as an *ism*.  Thus, a theory is first identified as an *ism*, the *pragmatic* operator is applied to it, and the result is another theory where the relationship with *practice* has been clarified.  Furthermore, self-application of this operator results in a fixed point, so that *pragmatic pragmaticism* results in *pragmaticism*.  
